pve: 
  host: dieSehnsucht
  ctid: 101
  name: Nginx
  vlan: 30
  zone: nginx_zone
os: 
  family: debian
  snapshot: bookworm
network: 
  address: 192.168.30.2/24
  gateway: 192.168.30.1
snapshots: 
  manual_packages: snapshots/nginx/manual-packages.txt
  running_services: snapshots/nginx/running-services.txt
  listening: snapshots/nginx/listening.txt
  docker_containers: null
observed_service_units: 
  - console-getty.service
  - container-getty@1.service
  - container-getty@2.service
  - cron.service
  - dbus.service
  - nezha-agent-cca8bee.service
  - nezha-agent.service
  - nginx-ui.service
  - nginx.service
  - postfix@-.service
  - ssh.service
  - systemd-journald.service
  - systemd-logind.service
  - systemd-networkd.service
manual_package_count: 272
