pve: 
  host: dieSehnsucht
  ctid: 102
  name: Tunnel
  vlan: 40
  zone: tunnel_zone
os: 
  family: debian
  snapshot: bookworm
network: 
  address: 192.168.40.2/24
  gateway: 192.168.40.1
snapshots: 
  manual_packages: snapshots/tunnel/manual-packages.txt
  running_services: snapshots/tunnel/running-services.txt
  listening: snapshots/tunnel/listening.txt
  docker_containers: null
observed_service_units: 
  - cloudflared.service
  - console-getty.service
  - container-getty@1.service
  - container-getty@2.service
  - cron.service
  - dbus.service
  - nezha-agent-69e0634.service
  - nezha-agent.service
  - postfix@-.service
  - ssh.service
  - systemd-journald.service
  - systemd-logind.service
  - systemd-networkd.service
manual_package_count: 270
