all: 
  children: 
    debian: 
      hosts: 
        bot-desuwa: 
          ansible_host: 192.168.50.5
          ansible_user: root
          pve_ctid: 153
          pve_name: bot-desuwa
        bot-diesw: 
          ansible_host: 192.168.50.4
          ansible_user: root
          pve_ctid: 152
          pve_name: bot-diesw
        coder: 
          ansible_host: 192.168.50.13
          ansible_user: root
          pve_ctid: 115
          pve_name: Coder
        coderunner: 
          ansible_host: 192.168.50.11
          ansible_user: root
          pve_ctid: 112
          pve_name: CodeRunner
        dockerhost: 
          ansible_host: 192.168.50.14
          ansible_user: root
          pve_vmid: 198
          pve_name: DockerHost
        kuma: 
          ansible_host: 192.168.60.3
          ansible_user: root
          pve_ctid: 113
          pve_name: Kuma
        nginx: 
          ansible_host: 192.168.30.2
          ansible_user: root
          pve_ctid: 101
          pve_name: Nginx
        tunnel: 
          ansible_host: 192.168.40.2
          ansible_user: root
          pve_ctid: 102
          pve_name: Tunnel
    docker: 
      hosts: 
        coder: 
          ansible_host: 192.168.50.13
          ansible_user: root
          pve_ctid: 115
          pve_name: Coder
        coderunner: 
          ansible_host: 192.168.50.11
          ansible_user: root
          pve_ctid: 112
          pve_name: CodeRunner
        dockerhost: 
          ansible_host: 192.168.50.14
          ansible_user: root
          pve_vmid: 198
          pve_name: DockerHost
        kuma: 
          ansible_host: 192.168.60.3
          ansible_user: root
          pve_ctid: 113
          pve_name: Kuma
    bots: 
      hosts: 
        bot-desuwa: 
          ansible_host: 192.168.50.5
          ansible_user: root
          pve_ctid: 153
          pve_name: bot-desuwa
        bot-diesw: 
          ansible_host: 192.168.50.4
          ansible_user: root
          pve_ctid: 152
          pve_name: bot-diesw
